software-challenge/backend

game_helper_clients/test_client/src/sc/TestClient.java

The gameEnded method from the IGameHandler can now be executed!

Fixed gameEnded

---

.gitignore
README.md
game_gui/build.xml

Das README dokumentiert die grobe Struktur des Repositorys und des Buildfiles.

Ein README und kleinere Bugfixes

---

game_plugins/hase_und_igel_2018/client/sc/plugin2018/AbstractClient.java
software_challenge_sdk/src/server_api/sc/networking/clients/ILobbyClientListener.java

Einfach ein paar kosmetische Verbesserungen

Improve AbstractClient

---

game_plugins/hase_und_igel_2018/shared/sc/plugin2018/Player.java

Correct fatal error in Player

---

gradle/build.gradle.kts

Set doc encoding to UTF-8

---

gradle/build.gradle.kts
player/build.gradle.kts
socha-sdk/src/server-api/sc/api/plugins/IGameState.kt

`moduleName` funktioniert aktuell nicht, dazu habe ich ein Issue geöffnet: https://github.com/Kotlin/dokka/issues/353
Ansonsten sieht alles soweit gut aus.
Fixes #190

Generate documentation via Dokka

---

plugin/src/shared/sc/plugin2019/Board.java
plugin/src/shared/sc/plugin2019/Field.java
plugin/src/shared/sc/plugin2019/FieldState.java
plugin/src/shared/sc/plugin2019/util/GameRuleLogic.java
socha-sdk/src/server-api/sc/api/plugins/IBoard.java
socha-sdk/src/server-api/sc/api/plugins/IField.java

Add copy constructor for Board, Field & equals for Board

---

gradle/build.gradle.kts
plugin/src/server/sc/plugin2019/Game.java
plugin/src/shared/sc/plugin2019/GameState.kt
plugin/src/shared/sc/plugin2019/util/Constants.java
plugin/src/test/sc/plugin2019/GamePlayTest.java
server/configuration/logback-release.xml
server/test/sc/server/plugins/TestGame.java
socha-sdk/src/framework/sc/shared/PlayerColor.kt
socha-sdk/src/framework/sc/shared/ScoreCause.java
socha-sdk/src/framework/sc/shared/WinCondition.java
socha-sdk/src/framework/sc/shared/WinReason.java
socha-sdk/src/server-api/sc/api/plugins/TwoPlayerGameState.kt
socha-sdk/src/server-api/sc/framework/plugins/RoundBasedGameInstance.java

[WIP] Rework Wincondition reporting

---

socha-sdk/src/test/sc/shared/GameResultTest.kt
socha-sdk/src/test/sc/shared/PlayerScoreTest.kt

Tests are failing due to ambiguity in what the actual output should be

test(sdk): add GameResult XML tests

---

plugin/src/server/sc/plugin2021/Game.kt
plugin/src/shared/sc/plugin2021/util/GameRuleLogic.kt
plugin/src/test/sc/plugin2021/GameRuleLogicTest.kt
plugin/src/test/sc/plugin2021/GameStateTest.kt
plugin/src/test/sc/plugin2021/GameTest.kt
plugin/src/test/sc/plugin2021/ManualGameTest.kts

More accurately, remove any color whose move threw an exception

fix(plugin): ensure that `PassMove`s throw and throws remove players

---

plugin/src/shared/sc/plugin2021/Team.kt

Fixes https://github.com/CAU-Kiel-Tech-Inf/backend/issues/290

fix(plugin): give each team the right list of colors

---

plugin/src/shared/sc/plugin2021/GameState.kt
plugin/src/shared/sc/plugin2021/Move.kt
plugin/src/shared/sc/plugin2021/util/GameRuleLogic.kt

Fixes https://github.com/CAU-Kiel-Tech-Inf/backend/issues/289

fix(plugin): remove off-by-one error in color removal calculation

---

README.md
gradle/build.gradle.kts
server/build.gradle.kts

chore(gradle): simplify deployment

---

gradle/build.gradle.kts
player/build.gradle.kts

Fixes `playerTest` on Windows. However, needs some adjustment, fix is currently hardcoded.

chore(gradle): fix playerTest on windows

---

gradle/build.gradle.kts
plugin/src/shared/sc/plugin2021/Board.kt
plugin/src/shared/sc/plugin2021/Coordinates.kt
plugin/src/shared/sc/plugin2021/PieceShape.kt
plugin/src/shared/sc/plugin2021/util/GameRuleLogic.kt

Still WIP because Dokka is mucking around

chore(gradle): update dokka

---

sdk/src/framework/sc/helpers/IAsyncResult.java
sdk/src/server-api/sc/api/plugins/host/IRequestResult.java
sdk/src/server-api/sc/networking/clients/LobbyClient.java
sdk/src/server-api/sc/protocol/helpers/AsyncResultManager.java
sdk/src/server-api/sc/protocol/helpers/RequestResult.kt

Nebenbei ein gutes Beispiel wie man Union Types in Kotlin via sealed classes umsetzt

Refactor Requestresult

---

plugin/src/shared/sc/plugin2021/GameState.kt
plugin/src/shared/sc/plugin2021/util/GameRuleLogic.kt
plugin/src/test/sc/plugin2021/GameStateTest.kt

GameState.deployedPieces isn't used anywhere but caused problems due to
not being serialised.
Fixes #313

fix(plugin): remove GameState's deployedPieces

---

plugin/src/shared/sc/plugin2021/Color.kt
sdk/src/framework/sc/shared/WelcomeMessage.kt

This reverts commit 025e31aa590a2994fdde02ba8f8f463e6a3fe22c.

refactor(plugin): remove backing lateinit field from Color's next

---

plugin/src/server/sc/plugin2021/Game.kt
plugin/src/shared/sc/plugin2021/util/Constants.kt
plugin/src/shared/sc/plugin2021/util/GameRuleLogic.kt
plugin/src/test/sc/plugin2021/GameTest.kt

Related to https://github.com/CAU-Kiel-Tech-Inf/gui/issues/39
Fixes #316

fix(plugin): make SkipMoves work properly, including a round limit

---

plugin/src/server/sc/plugin2021/Game.kt
plugin/src/shared/sc/plugin2021/GameState.kt
plugin/src/test/sc/plugin2021/GameTest.kt

fix(plugin): determine scores properly at the end of a game

---

plugin/src/test/sc/plugin2021/GameTest.kt

Somewhat POC, but I'm starting to like the new style already :)

test(plugin): migrate GameTest to WordSpec

---

README.md

@SKoschnicke @anarchuser were these the Specs we settled on? I know that this was only an intermediate draft.

docs(readme): add testing information & improve setup instructions

---

plugin/src/test/sc/plugin2021/BoardTest.kt
plugin/src/test/sc/plugin2021/GameRuleLogicTest.kt
plugin/src/test/sc/plugin2021/GameStateTest.kt
plugin/src/test/sc/plugin2021/GameTest.kt
server/test/sc/server/network/ConnectionTest.java
server/test/sc/server/network/RealServerTest.kt
server/test/sc/server/network/RequestTest.kt
server/test/sc/server/plugins/TestPlugin.kt

Only redundancies and oversights, should change nothing functionally

Some test cleanups

---

plugin/src/shared/sc/plugin2021/Move.kt
server/src/sc/server/gaming/GameRoom.java

Shouldn't break anything, made a PR just to be sure.

Fix some stuff

---

sdk/src/server-api/sc/networking/TcpNetwork.java
sdk/src/server-api/sc/networking/clients/XStreamClient.java
sdk/src/server-api/sc/protocol/responses/CloseConnection.kt
sdk/src/server-api/sc/protocol/responses/MementoEvent.kt
server/src/sc/server/network/Client.java

`LobbyTest.shouldConnectAndDisconnect` was annoying me. While debugging it, I tackled some other issues as well that hopefully make debugging easier in the future.
rebase merge

Improve XStreamClient & fix LobbyTest

---

plugin/src/test/sc/plugin2021/GameTest.kt
sdk/src/server-api/sc/framework/plugins/AbstractGame.kt

Should fix https://github.com/CAU-Kiel-Tech-Inf/gui/issues/38

send final state to listeners before game over

---

.gitignore
helpers/test-client/build.gradle.kts
helpers/test-client/src/sc/TestClient.java
sdk/src/server-api/sc/networking/clients/XStreamClient.java

Needs #352 to work, but then it does work nicely, including some improvements!
Try `:test-client:run` (to prevent XStream issues, you can locally rebase on `xstream-synchronization`), it should work automagically :)

Fix TestClient

---

.travis.yml
gradle/build.gradle.kts
helpers/test-client/src/logback-tests.xml
helpers/test-client/src/sc/TestClient.java
player/build.gradle.kts
server/configuration/logback-production.xml
server/configuration/logback-release.xml
server/configuration/logback.xml

TODO: load logback config from resources instead of custom folders

Improve logback config

---

player/src/main/sc/player2021/Starter.java
player/src/main/sc/player2021/logic/Logic.java
plugin/src/client/sc/plugin2021/IGameHandler.kt
plugin/src/client/sc/plugin2021/PlayerClient.kt
sdk/build.gradle.kts
sdk/src/player/sc/player/IGameHandler.kt
sdk/src/player/sc/player/PlayerClient.kt

Since this changes the interface for participants, maybe something to postpone a bit, unless we're not planning any more releases this season.

feat(player): decouple Logic, Starter and PlayerClient

---

.gitignore
server/src/sc/server/gaming/GameRoom.java
server/test/sc/server/gaming/GameRoomTest.kt

Rather than through an observer that connects to the server as a separate client.
Still needs testing.

Record replays directly in GameRoom

---

gradle/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
helpers/test-client/build.gradle.kts
player/build.gradle.kts
player/src/main/sc/player2022/Starter.java
sdk/src/main/server-api/sc/networking/clients/AbstractLobbyClientListener.kt
sdk/src/main/server-api/sc/networking/clients/ILobbyClientListener.kt
sdk/src/main/server-api/sc/networking/clients/LobbyClient.java
sdk/src/main/server-api/sc/networking/clients/XStreamClient.java
server/build.gradle.kts
server/src/test/java/sc/server/client/TestLobbyClientListener.java

Feels like a miracle: No exceptions at the end of a regular game anymore :o
Also, to use Java 16+ we needed to add some Add-Opens.
Fixes #406, Fixes #405

Disconnect players gracefully after a game and add Java 16+ compatibility

---

plugin/src/main/kotlin/sc/plugin2023/GameState.kt

fix(plugin/GameState): correctly clone fishes array
